services:
  telegram:
    image: 'vrokka/poker-clock-tg-bot:latest'
    environment:
      - 'DB_PASSWORD=r8E6&r3>'
      - 'DB_URL=jdbc:postgresql://postgres:5432/pokerclock?sslmode=disable'
      - 'DB_USER=psuser'
      - 'PROFILES=production,postgres'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:16.1'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=psuser'
      - 'POSTGRES_DB=pokerclock'
      - 'POSTGRES_PASSWORD=r8E6&r3>'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data