name: Poker Clock App build

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: pokerclock-lib
          path: 'lib/build/libs/*.jar'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: pokerclock-telegram
          path: 'telegram/build/libs/*.jar'

      - name: Run integration tests
        run: ./gradlew integrationTest

