name: Deploy to remote

on:
  #  workflow_run:
  #    workflows: [ "Poker Clock App build" ]
  #    types:
  #      - completed
  #    branches:
  #      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_CMD_ARGS: "-6"
          SCRIPT_BEFORE: |
            whoami
            ls -al