name: Deploy to remote

on:
  #  workflow_run:
  #    workflows: [ "Poker Clock App build" ]
  #    types:
  #      - completed
  #    branches:
  #      - master

  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: testing ipv6 for command
        run: |
          curl -m 9 --ipv6 --verbose https://google.com

      - name: testing ipv6
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
            ls -l