name: Deploy to remote

on:
#  workflow_run:
#    workflows: [ "Poker Clock App build" ]
#    types:
#      - completed
#    branches:
#      - master

  push:
    branches:
      - master
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
            echo "Run list"
            echo $(gh run list -R ${{ github.repository }} -w "Poker Clock App build"  -L 1 --json databaseId -q '.[].databaseId') >> $RUNID
#            echo "API call"
#            echo $(gh api repos/mrrockka/poker.clock/actions/workflows/build.yml/runs?event=push&branch=master)

      - name: test2
        run: echo $RUNID

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: Download telegram bot jar
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.run_id }}
          name: telegram-bot
          path: ./

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          rm: false
          source: "telegram-bot-*.jar"
          target: "~/app"

      - name: execute scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            ls -l