name: Deploy to remote

on:
  workflow_run:
    workflows: [ "Poker Clock App build" ]
    types:
      - completed
    branches:
      - master

  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: |
            echo "Run list"
            echo "runid=$(gh run list -R ${{ github.repository }} -w "Poker Clock App build"  -L 1 --json databaseId -q '.[].databaseId')" >> "$GITHUB_OUTPUT"

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - uses: actions/checkout@v4

      - name: Download telegram bot jar
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.setup.outputs.runid }}
          name: telegram-bot
          path: ./app/

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          overwrite: true
          source: "./app/telegram-bot-*.jar,./scripts"
          target: "~/app"

      - name: execute scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            ls -l