name: Deploy to remote

on:
  workflow_run:
    workflows: [ "Poker Clock App build" ]
    types:
      - completed
    branches:
      - master

  #  push:
  #    branches:
  #      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: Download telegram bot jar
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: telegram-bot
          path: ./

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          rm: false
          source: "telegram-bot-*.jar"
          target: "~/app"

      - name: execute scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            ls -l